# Generated by Django 5.2.6 on 2026-01-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='comentario_validacion',
            field=models.TextField(blank=True),
        ),
    ]
